### PR TITLE
Fix pathing near other groups

### PR DESCRIPTION
**Pull request by brianpeiris**
Previously, pathing would fail if you tried to path near a separate group which had a poly with a centroid that is closer than the current poly's centroid. 

This fix adds a `checkPolygon` flag to `getGroup` that will check for an exact poly match and return the corresponding group. If an exact match is not found, the previous behavior is still in effect and `getGroup` will return the group of the closest node.

For example, in the demo level there is a small group hidden inside the column that breaks this pathing:

image

### CODE REVIEW

**Comment by donmccurdy** [comment]
Don't worry about the failing CI, I need to configure it to build the project before running tests (https://github.com/donmccurdy/three-pathfinding/issues/22). Will review this soon.

**Comment by donmccurdy** [comment]
Looks good but needs a rebase in the tests. :)

**Comment by donmccurdy** [comment]
Resolved, thanks again!

**Comment by brianpeiris** [comment]
Thanks for the quick merge!

**Pull request merged**
